### ISSUE TITLE
change the name of the `arjun` branch

### ISSUE THREAD

**Issue by asarode** [AndrewSB/board-bullets#1]
I suggest changing it to `sarode`, `baller`, `beast`. Any of the these should be good :smile:

**Comment by AndrewSB** [comment]
[Come at me](http://www.casleyconsulting.co.jp/blog-engineer/wp-content/uploads/sites/12/2013/05/pullrequest1.png) bro

**Comment by AndrewSB** [comment]
+1 for baller

**Comment by asarode** [comment]
`git pull && git checkout baller && git branch -D arjun`
There you go.

**Comment by AndrewSB** [comment]
d2b6bb870f74b8eea1fc7cc712470449b9ebd250 ❤️

**Comment by asarode** [comment]
:heart:
